name: Meterian Scanner workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Vulnerability scan
            uses: MeterianHQ/meterian-github-action@develop
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                args: "" ## placeholder for METERIAN_CLI_ARGS