language: node_js

services: 
  - docker

before_install:
  - | 
    docker run -it --rm \
    --volume ${PWD}:/workspace --env METERIAN_API_TOKEN=$METERIAN_API_TOKEN \
    meterian/cli

install:
  - npm install --prod