version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@0.5.20
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install -prod
            - run: npm test
  meterian:
    machine: true
    steps: 
      - checkout
      - run: docker run -it --rm --volume ${PWD}:/workspace --env METERIAN_API_TOKEN=$METERIAN_API_TOKEN meterian/cli
workflows:
    build-and-test: 
      jobs:
        - build-and-test
        - meterian