version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
              - name: Meterian
              - command: bash <(wget -O /tmp/meterian-cli.jar https://www.meterian.com/downloads/meterian-cli.jar)
            - run: java -Denv=qa -jar /tmp/meterian-cli.js
            - run: npm install -prod
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test