version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install -prod
            - run: npm test
  meterian:
    executor:
      machine:
       image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - get-meterian: 
        -run:
          name: Get meterian client
          command: bash <(wget /tmp/meterian-cli.jar https://www.meterian.com/downloads/meterian-cli.jar)
      - run-meterian:
        -run: java -Denv=qa -jar /tmp/meterian-cli.jar
workflows:
    build-and-test: 
      jobs:
        - build-and-test
        - meterian